basePath: /api/v1
info:
  contact: {}
  description: Simple API to manage Farms and Ponds
  termsOfService: http://swagger.io/terms/
  title: DA Farm Backend
  version: "1.0"
paths:
  /misc/ping:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: check server status
      tags:
      - misc
swagger: "2.0"
